# Generated by Django 5.0 on 2023-12-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberstotextapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversions',
            name='original_number',
            field=models.IntegerField(),
        ),
    ]
