# Generated by Django 5.0 on 2023-12-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberstotextapp', '0002_alter_conversions_original_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversions',
            name='converted_number',
            field=models.TextField(),
        ),
    ]
